"""add disputes dispute_evidences and audit_logs tables

Revision ID: 23f2f2380a90
Revises: 2c87d33d1e0c
Create Date: 2026-09-05 21:00:42.559701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23f2f2380a90'
down_revision: Union[str, Sequence[str], None] = '2c87d33d1e0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'disputes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('transaction_id', sa.Integer(), nullable=False),
        sa.Column('opened_by_user_id', sa.Integer(), nullable=False),
        sa.Column('reason', sa.String(length=80), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('status', sa.Enum('open', 'under_review', 'awaiting_evidence', 'escalated', 'resolved', name='disputestatus'), nullable=False),
        sa.Column('priority', sa.String(length=20), nullable=False),
        sa.Column('resolution_notes', sa.Text(), nullable=True),
        sa.Column('resolved_by_user_id', sa.Integer(), nullable=True),
        sa.Column('resolved_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['opened_by_user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disputes_id'), 'disputes', ['id'], unique=False)
    op.create_index(op.f('ix_disputes_opened_by_user_id'), 'disputes', ['opened_by_user_id'], unique=False)
    op.create_index(op.f('ix_disputes_resolved_by_user_id'), 'disputes', ['resolved_by_user_id'], unique=False)
    op.create_index(op.f('ix_disputes_transaction_id'), 'disputes', ['transaction_id'], unique=False)

    op.create_table(
        'dispute_evidences',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('dispute_id', sa.Integer(), nullable=False),
        sa.Column('uploaded_by_user_id', sa.Integer(), nullable=False),
        sa.Column('evidence_type', sa.String(length=50), nullable=False),
        sa.Column('file_name', sa.String(length=200), nullable=False),
        sa.Column('file_path', sa.String(length=500), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['dispute_id'], ['disputes.id'], ),
        sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispute_evidences_dispute_id'), 'dispute_evidences', ['dispute_id'], unique=False)
    op.create_index(op.f('ix_dispute_evidences_id'), 'dispute_evidences', ['id'], unique=False)
    op.create_index(op.f('ix_dispute_evidences_uploaded_by_user_id'), 'dispute_evidences', ['uploaded_by_user_id'], unique=False)

    op.create_table(
        'audit_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('actor_user_id', sa.Integer(), nullable=True),
        sa.Column('action', sa.String(length=100), nullable=False),
        sa.Column('entity_type', sa.String(length=50), nullable=False),
        sa.Column('entity_id', sa.Integer(), nullable=False),
        sa.Column('details', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')

    op.drop_index(op.f('ix_dispute_evidences_uploaded_by_user_id'), table_name='dispute_evidences')
    op.drop_index(op.f('ix_dispute_evidences_id'), table_name='dispute_evidences')
    op.drop_index(op.f('ix_dispute_evidences_dispute_id'), table_name='dispute_evidences')
    op.drop_table('dispute_evidences')

    op.drop_index(op.f('ix_disputes_transaction_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_resolved_by_user_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_opened_by_user_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_id'), table_name='disputes')
    op.drop_table('disputes')
    # ### end Alembic commands ###
