"""Initial schema with core domain models

Revision ID: 34b9b2f7290d
Revises: 
Create Date: 2026-09-04 22:25:32.836809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34b9b2f7290d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=120), nullable=False),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('business_type', sa.String(length=80), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('unverified', 'pending_review', 'verified', 'escalated', 'suspended', name='buyerstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyers_id'), 'buyers', ['id'], unique=False)
    op.create_table('commodities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('variety', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('is_perishable', sa.Boolean(), nullable=False),
    sa.Column('perishability_profile', sa.String(length=200), nullable=True),
    sa.Column('grading_parameters', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_commodities_id'), 'commodities', ['id'], unique=False)
    op.create_table('fpos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('registration_number', sa.String(length=80), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('collection_center', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'pending_verification', name='fpostatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fpos_id'), 'fpos', ['id'], unique=False)
    op.create_table('markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_markets_id'), 'markets', ['id'], unique=False)
    op.create_table('storage_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('capacity_kg', sa.Float(), nullable=True),
    sa.Column('commodity_suitability', sa.String(length=200), nullable=True),
    sa.Column('cost_per_quintal', sa.Float(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storage_options_id'), 'storage_options', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('role', sa.Enum('farmer', 'fpo_manager', 'buyer', 'field_agent', 'admin', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('farmers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('village', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farmers_id'), 'farmers', ['id'], unique=False)
    op.create_index(op.f('ix_farmers_phone'), 'farmers', ['phone'], unique=True)
    op.create_index(op.f('ix_farmers_user_id'), 'farmers', ['user_id'], unique=False)
    op.create_table('market_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('commodity_id', sa.Integer(), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('min_price', sa.Float(), nullable=True),
    sa.Column('max_price', sa.Float(), nullable=True),
    sa.Column('modal_price', sa.Float(), nullable=True),
    sa.Column('arrival_volume', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_prices_commodity_id'), 'market_prices', ['commodity_id'], unique=False)
    op.create_index(op.f('ix_market_prices_id'), 'market_prices', ['id'], unique=False)
    op.create_index(op.f('ix_market_prices_market_id'), 'market_prices', ['market_id'], unique=False)
    op.create_index(op.f('ix_market_prices_price_date'), 'market_prices', ['price_date'], unique=False)
    op.create_table('fpo_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fpo_id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('membership_status', sa.Enum('active', 'inactive', 'pending', name='membershipstatus'), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.ForeignKeyConstraint(['fpo_id'], ['fpos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fpo_members_farmer_id'), 'fpo_members', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_fpo_members_fpo_id'), 'fpo_members', ['fpo_id'], unique=False)
    op.create_index(op.f('ix_fpo_members_id'), 'fpo_members', ['id'], unique=False)
    op.create_table('produce_lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('commodity_id', sa.Integer(), nullable=True),
    sa.Column('crop', sa.String(length=100), nullable=False),
    sa.Column('quantity_kg', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('quality_grade', sa.String(length=20), nullable=False),
    sa.Column('moisture_percent', sa.Float(), nullable=True),
    sa.Column('harvest_date', sa.Date(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('expected_price_per_kg', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produce_lots_commodity_id'), 'produce_lots', ['commodity_id'], unique=False)
    op.create_index(op.f('ix_produce_lots_farmer_id'), 'produce_lots', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_produce_lots_id'), 'produce_lots', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_produce_lots_id'), table_name='produce_lots')
    op.drop_index(op.f('ix_produce_lots_farmer_id'), table_name='produce_lots')
    op.drop_index(op.f('ix_produce_lots_commodity_id'), table_name='produce_lots')
    op.drop_table('produce_lots')
    op.drop_index(op.f('ix_fpo_members_id'), table_name='fpo_members')
    op.drop_index(op.f('ix_fpo_members_fpo_id'), table_name='fpo_members')
    op.drop_index(op.f('ix_fpo_members_farmer_id'), table_name='fpo_members')
    op.drop_table('fpo_members')
    op.drop_index(op.f('ix_market_prices_price_date'), table_name='market_prices')
    op.drop_index(op.f('ix_market_prices_market_id'), table_name='market_prices')
    op.drop_index(op.f('ix_market_prices_id'), table_name='market_prices')
    op.drop_index(op.f('ix_market_prices_commodity_id'), table_name='market_prices')
    op.drop_table('market_prices')
    op.drop_index(op.f('ix_farmers_user_id'), table_name='farmers')
    op.drop_index(op.f('ix_farmers_phone'), table_name='farmers')
    op.drop_index(op.f('ix_farmers_id'), table_name='farmers')
    op.drop_table('farmers')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_storage_options_id'), table_name='storage_options')
    op.drop_table('storage_options')
    op.drop_index(op.f('ix_markets_id'), table_name='markets')
    op.drop_table('markets')
    op.drop_index(op.f('ix_fpos_id'), table_name='fpos')
    op.drop_table('fpos')
    op.drop_index(op.f('ix_commodities_id'), table_name='commodities')
    op.drop_table('commodities')
    op.drop_index(op.f('ix_buyers_id'), table_name='buyers')
    op.drop_table('buyers')
    # ### end Alembic commands ###
