"""create demands table

Revision ID: e5132dca9f82
Revises: 280339cb3fcf
Create Date: 2026-09-05 15:46:04.036651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5132dca9f82'
down_revision: Union[str, Sequence[str], None] = '280339cb3fcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('commodity_id', sa.Integer(), nullable=False),
    sa.Column('required_quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('minimum_grade', sa.String(length=20), nullable=True),
    sa.Column('delivery_location', sa.String(length=200), nullable=True),
    sa.Column('required_by', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('active', 'fulfilled', 'expired', 'cancelled', name='demandstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demands_buyer_id'), 'demands', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_demands_commodity_id'), 'demands', ['commodity_id'], unique=False)
    op.create_index(op.f('ix_demands_id'), 'demands', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_demands_id'), table_name='demands')
    op.drop_index(op.f('ix_demands_commodity_id'), table_name='demands')
    op.drop_index(op.f('ix_demands_buyer_id'), table_name='demands')
    op.drop_table('demands')
    # ### end Alembic commands ###
