"""create offers and offer_histories tables

Revision ID: fc1c3eb271cd
Revises: e5132dca9f82
Create Date: 2026-09-05 19:49:52.453172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc1c3eb271cd'
down_revision: Union[str, Sequence[str], None] = 'e5132dca9f82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('demand_id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('offered_price', sa.Float(), nullable=False),
    sa.Column('pickup_window', sa.String(length=200), nullable=False),
    sa.Column('payment_terms', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('submitted', 'countered', 'accepted', 'rejected', 'expired', name='offerstatus'), nullable=False),
    sa.Column('parent_offer_id', sa.Integer(), nullable=True),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ),
    sa.ForeignKeyConstraint(['demand_id'], ['demands.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['produce_lots.id'], ),
    sa.ForeignKeyConstraint(['parent_offer_id'], ['offers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offers_buyer_id'), 'offers', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_offers_demand_id'), 'offers', ['demand_id'], unique=False)
    op.create_index(op.f('ix_offers_farmer_id'), 'offers', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_offers_id'), 'offers', ['id'], unique=False)
    op.create_index(op.f('ix_offers_lot_id'), 'offers', ['lot_id'], unique=False)
    op.create_index(op.f('ix_offers_parent_offer_id'), 'offers', ['parent_offer_id'], unique=False)
    op.create_table('offer_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('from_status', sa.Enum('submitted', 'countered', 'accepted', 'rejected', 'expired', name='offerstatus'), nullable=True),
    sa.Column('to_status', sa.Enum('submitted', 'countered', 'accepted', 'rejected', 'expired', name='offerstatus'), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('offered_price', sa.Float(), nullable=True),
    sa.Column('pickup_window', sa.String(length=200), nullable=True),
    sa.Column('payment_terms', sa.String(length=200), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offer_histories_id'), 'offer_histories', ['id'], unique=False)
    op.create_index(op.f('ix_offer_histories_offer_id'), 'offer_histories', ['offer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offer_histories_offer_id'), table_name='offer_histories')
    op.drop_index(op.f('ix_offer_histories_id'), table_name='offer_histories')
    op.drop_table('offer_histories')
    op.drop_index(op.f('ix_offers_parent_offer_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_lot_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_farmer_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_demand_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_buyer_id'), table_name='offers')
    op.drop_table('offers')
    # ### end Alembic commands ###
